### ISSUE TITLE
Remove destructive code from Readme

### ISSUE THREAD

**Issue by YitzhakRabin** [netaneld122/firmware-variables#3]
It's not okay to just put code that destroys your main boot entry in the readme file with no warnings or documentation / description.
Don't you think it'll be better to include in the readme only code that doesn't modify the system state? All other code examples can be moved to the examples directory.
Also I think all code examples (both in the readme file and in the examples directory) should be documented

**Comment by netaneld122** [comment]
I planned to improve the documentation so that will be my next patch,
but generally, since 50% of the library API is modifying the system state by design, I don't see any problem in showing examples that modify the system state.  
I will definitely add a warning and perhaps make the examples less destructive.
